server {
    listen       ${PORT};
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # 1. Entry points - Always revalidate with the server
    location ~* \.(?:html|json)$ {
        add_header Cache-Control "no-cache, must-revalidate";
        expires 0;
    }

    # 2. Service Worker and Bootstrap
    location ~* (?:flutter_service_worker\.js|flutter_bootstrap\.js)$ {
        add_header Cache-Control "no-cache, must-revalidate";
        expires 0;
    }

    # 3. Static Assets
    location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf)$ {
        add_header Cache-Control "public, max-age=31536000";
        add_header Access-Control-Allow-Origin *;
        expires 30d;
    }

    location / {
        # This line is crucial for Flutter web routing
        try_files $uri $uri/ /index.html;
    }

    # Optional: Enable Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype image/svg+xml image/x-icon;
}
